### PR TITLE
Minor fixes

### LINKED ISSUE #142: service avatar too big when swiping to next page
page 1:
Screenshot 2019-06-18 at 09 26 47

page 2:
Screenshot 2019-06-18 at 09 28 13

### LINKED ISSUE #144: Multiple file components in 1 section
- [x] When the activity result arrives, all components respond to it instead of only the current component.
- [x] In case of an upload error, a thick gray line is shown.

Screenshot 2019-06-20 at 15 55 43

### PR DESCRIPTION
**Pull request by lucasvanhalst**
Closes #144
Closes #142

### CODE REVIEW

File: rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java [hunk 1]
```diff
@@ -235,6 +236,13 @@ protected void safeRun() {
                     L.bug("Error while executing JSMFR\nStack: %s\nSource: %s", e.getJSStackTrace(), sourceLine);
                 } catch (Exception e) {
                     L.bug("JsMfr Exception", e);
+                } catch (Error e) {
+                    if (e.getMessage().contains("Invalid V8 access")) {
+                        // Thread killed, not much we can do about it
+                        L.d(e);
+                    } else {
+                        throw e;
```
Comment (RubenMattan) [inline rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java]: don't change the behaviour, just do L.bug as before

File: rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java [hunk 2]
```diff
@@ -253,8 +261,8 @@ private static void releaseV8Runtime() {
         long fiveMinutesAgo = System.currentTimeMillis() - FIVE_MINUTES;
         if (sV8LastUsedTime <= fiveMinutesAgo && sV8Runtime != null) {
             L.d("Releasing V8 runtime");
-            sJSConsole.release();
-            sV8Runtime.release();
+            sJSConsole.close();
+            sV8Runtime.release(BuildConfig.DEBUG);
```
Comment (RubenMattan) [inline rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java]: always report memory leaks not just during debug

Comment (lucasvanhalst) [reply rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java]: It throws an error when enabled so I don't really want to enable it for users

Comment (RubenMattan) [reply rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java]: the current behaviour is always report memory leaks, i would not change this.
Reason: we would never know if there is an issue since we test these things in production apps...

File: rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java [hunk 3]
```diff
@@ -237,12 +236,7 @@ protected void safeRun() {
                 } catch (Exception e) {
                     L.bug("JsMfr Exception", e);
                 } catch (Error e) {
-                    if (e.getMessage().contains("Invalid V8 access")) {
-                        // Thread killed, not much we can do about it
-                        L.d(e);
-                    } else {
-                        throw e;
-                    }
+                    L.bug(e);
```
Comment (RubenMattan) [inline rogerthat/src/main/java/com/mobicage/rogerthat/plugins/messaging/mfr/JsMfr.java]:
```java
if (e.getMessage().contains("Invalid V8 access")) {
    // Thread killed, not much we can do about it	
    L.d(e);	
} else {	
    L.bug(e);
}
```
